spring:
  application:
    name: xxl-job-test
xxl:
  job:
    access-token:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      appname: ${spring.application.name}
      address:
      ip:
      port: -1
      logpath: /data/applogs/xxl-job-test/jobhandler
      logretentiondays: 3
